spring.application.name=ApiGateway
server.port=8080

# Drone Service
spring.cloud.gateway.server.webmvc.routes[0].id=drone-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/drone/**

# Package Service
spring.cloud.gateway.server.webmvc.routes[1].id=package-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/package/**

# Route Service
spring.cloud.gateway.server.webmvc.routes[2].id=route-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/route/**

# Delivery Service
spring.cloud.gateway.server.webmvc.routes[3].id=delivery-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/delivery/**